config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  constraints subdomain: 'www' do
    get ':any', to: redirect(subdomain: nil, path: '/%{any}'), any: /.*/
  end

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: "prehome#index"
  get 'settings/unsubscribe'
  get '/home', to: 'home#index'
  get '/politicians', to: 'pages#politicians'
  get '/terms', to: 'pages#terms'
  get '/diplomado-innovacion-politica', to: 'pages#diplomat'
  get '/partidos-politicos-en-la-era-digital', to: 'pages#digital_era', as: 'digital_era'
  get '/mapeo-de-infraestructuras-civicas', to: 'pages#maping', as: 'maping'

  namespace :admin do
    resources :tags
    resources :polls, except: [:show] do
      patch 'toggle_active_flag'
    end
    resources :users, only: [:index, :edit, :update, :destroy] do
      collection do
        get 'permits'
      end
    end
    resources :dashboard, only: [:index]
    get '/dashboard/stats', to: 'dashboard#stats'
  end

  resources :subscriptions, only: [:create, :destroy]
  resources :users , except: [:show] do
    get 'already_voted', on: :member
    get 'validate', on: :member
    patch 'update_valid_user', on: :member
    post 'interests', to: 'interests#association', format: 'json'
  end

  get '/check_session', to: 'sessions#show', format: 'json'
  delete '/sessions', to: 'sessions#destroy', as: 'session'
  delete '/destroy_facebook_session', to: 'sessions#destroy_facebook_session'
  post '/sessions', to: 'sessions#create', format: 'json'
  get '/mail_preview', to: 'messages#preview'

  get '/auth/sessions', to: 'sessions#error'
  resources :users, only: [:show]
  get '/proponents/:id', to: 'users#politician_profile', as: :politician_profile
  get 'polls/closed', to: 'polls#index_closed', format: 'json'
  get 'check_vote', to: 'votes#check_vote', format: 'json'
  get 'random_polls', to: 'polls#random_non_voted_polls', format: 'json'
  get 'summary_polls', to: 'polls#summary_polls', format: 'json'

  resources :polls do
    get 'last', on: :collection
    get 'voted', on: :collection
    get 'search', on: :collection, to: 'polls#search'
  end

  resources :votes, only: :create
  resources :tags, only: [:show, :index]
  resources :admin, only: [:create, :new, :edit]
  scope '/admin', as: :admin do
    resources :email_lists
    get '/mail', to: 'messages#new'
    post '/mail', to: 'messages#create'
    get '/mail_preview', to: 'messages#preview'
    # get '/', to: 'sessions#new'
    get '/', to: 'sessions#new', as: :login
    post '/sessions', to: 'sessions#admin_create'
    get 'validate-users', to: 'admin/users#index'
  end

  get 'settings/unsubscribe'
  get 'settings/successfully_unsubscribed'
  patch 'settings/update'

  mount SimpleDiscussion::Engine => "/foro"
end

app/controllers/admin/polls_controller.rb
class Admin::PollsController < ApplicationController
  before_action :validate_admin_or_politician, only: [:index, :edit, :update]
  before_action :validate_politician, except: [:index, :edit, :update, :toggle_active_flag, :one_day_away_from_first_debate_notification, :one_day_away_from_second_debate_notification]
  before_action :validate_superadmin, only: [:toggle_active_flag, :one_day_away_from_first_debate_notification, :one_day_away_from_second_debate_notification]
  before_action :set_poll, only: %i(edit update destroy toggle_active_flag one_day_away_from_first_debate_notification one_day_away_from_second_debate_notification)
  before_action :bind_links, only: %i(create update)
  before_action :set_tags, only: %i(create update)

  include VotesHelper

  def create
    if @poll.save
      notify_administrators_about_new_poll
      flash[:success] = "La propuesta fue creada correctamente"
      redirect_to admin_polls_path
    else
      flash[:success] = "La propuesta no pudo ser creada, intente de nuevo por favor"
      render :new
    end
  end

  def update
    if @poll.update(poll_params.except(:user_id))
      flash[:success] = "Propuesta correctamente actualizada"
      if @poll.state == "Radica concejal"
        notify_poll_settled
        @poll.specs['poll_settled_notification_sent'] = true
      elsif @poll.state == "Primer debate"
        notify_first_debate_scheduled
        @poll.specs['first_debate_sheduled_notification_sent'] = true
      elsif @poll.state == "Segundo debate" && Poll.poll_types[@poll.poll_type] == 1
        notify_second_debate_scheduled
        @poll.specs['second_debate_sheduled_notification_sent'] = true
      elsif @poll.state == "Sanción del proyecto de acuerdo" && Poll.poll_types[@poll.poll_type] == 0
        notify_motion_of_censure
        @poll.specs['motion_of_censure_notification_sent'] = true
      elsif @poll.state == "Sanción del proyecto de acuerdo" && Poll.poll_types[@poll.poll_type] == 1
        notify_agreemen_sanction
        @poll.specs['agreement_sanction_notification_sent'] = true
      end
      @poll.save
      redirect_to admin_polls_path
    else
      render :edit
    end
  end

  def destroy
    @poll.destroy
    flash[:success] = "Propuesta eliminada"
    redirect_to admin_polls_path
  end

  def edit
    @used_tags = @poll.tags.map(&:name).join(',')
  end

  def index
    @filtered_polls = Poll.includes(:tags, votes: [:user]).by_title(params[:search_term]).by_status(params[:status])
    @filtered_polls = params[:status] == 'inactive' ? @filtered_polls.inactive : @filtered_polls
    @polls = if current_user.politico?
              Kaminari.paginate_array(@filtered_polls.select{ |p| p.user_id == current_user.id}).page(params[:page]).per(4)
             else
              Kaminari.paginate_array(@filtered_polls).page(params[:page]).per(4)
             end
  end

  def new
    @poll = Poll.new
  end


  def toggle_active_flag
    @poll.active = !@poll.active
    if @poll.save && @poll.active?
      flash[:success] = "propuesta publicada!"
      notify_users_about_new_poll
      schedule_voting_reminder unless @poll.closed?
      schedule_voting_closed_notification unless @poll.closed?
      @poll.specs['new_poll_mail_sent'] = true
      @poll.specs['voting_reminder_sent'] = true
      @poll.specs['voting_closed_notification_sent'] = true
      @poll.save
    elsif @poll.save && !@poll.active?
      flash[:success] = "propuesta oculta al público"
    else
      flash[:error] = "La propuesta no pudo ser actualizada, intente nuevamente"
    end
    redirect_to :back
  end

  def one_day_away_from_first_debate_notification
    return if @poll.specs['one_day_left_for_first_debate_notification_sent'] == true
    set_random_polls
    receivers = @poll.votes.map(&:user).uniq
    receivers.each do |receiver|
      UserNotifierMailer.one_day_away_from_first_debate(@poll, receiver, @random_polls).deliver_now
    end
    flash[:success] = "Notificación enviada: A un día del primer debate"
    @poll.specs['one_day_left_for_first_debate_notification_sent'] = true
    @poll.save
    redirect_to :back
  end

  def one_day_away_from_second_debate_notification
    return if @poll.specs['one_day_left_for_second_debate_notification_sent'] == true
    set_random_polls
    receivers = @poll.votes.map(&:user).uniq
    receivers.each do |receiver|
      UserNotifierMailer.one_day_away_from_second_debate(@poll, receiver, @random_polls).deliver_now
    end
    flash[:success] = "Notificación enviada: A un día del primer debate"
    @poll.specs['one_day_left_for_second_debate_notification_sent'] = true
    @poll.save
    redirect_to :back
  end

  private

    def notify_administrators_about_new_poll
      User.administrador.each do |admin|
        AdminNotifierMailer.new_poll_created(@poll, current_user, admin).deliver_later
      end
    end

    def notify_users_about_new_poll
      return if @poll.specs['new_poll_mail_sent'] == true
      set_random_polls
      receivers = related_users
      # if poll is from a new author or theme, notify all users
      receivers = User.all if (@related_by_author.count < 2) || (@related_by_theme.count < 2)
      receivers.each do |receiver|
        UserNotifierMailer.send_new_poll_mail(@poll, receiver, @random_polls).deliver_later
      end
    end

    def schedule_voting_reminder
      return if @poll.specs['voting_reminder_sent'] == true
      set_random_polls
      receivers = related_users - @poll.votes.map(&:user)
      days_from_today = (@poll.closing_date - Date.today).to_i / 2
      receivers.each do |receiver|
        UserNotifierMailer.poll_voting_reminder(@poll, receiver, @random_polls).deliver_later(wait_until: days_from_today.days.from_now) if days_from_today.positive?
      end
    end

    def schedule_voting_closed_notification
      return if @poll.specs['voting_closed_notification_sent'] == true
      set_random_polls
      receivers = @poll.votes.map(&:user).uniq
      days_from_today = (@poll.closing_date - Date.today).to_i
      receivers.each do |receiver|
        UserNotifierMailer.poll_closed_notification(@poll, receiver, @random_polls, vote_count(@poll)).deliver_later(wait_until: days_from_today.days.from_now.end_of_day)
      end
    end


    def notify_poll_settled
      return if @poll.specs['poll_settled_notification_sent'] == true
      set_random_polls
      receivers = @poll.votes.map(&:user).uniq
      receivers.each do |receiver|
        UserNotifierMailer.poll_settled_mail(@poll, receiver, @random_polls).deliver_now
      end
    end

    def notify_first_debate_scheduled
      return if @poll.specs['first_debate_sheduled_notification_sent'] == true
      set_random_polls
      receivers = @poll.votes.map(&:user).uniq
      receivers.each do |receiver|
        UserNotifierMailer.first_debate_scheduled(@poll, receiver, @random_polls).deliver_now
      end
    end

    def notify_second_debate_scheduled
      return if @poll.specs['second_debate_sheduled_notification_sent'] == true
      set_random_polls
      receivers = @poll.votes.map(&:user).uniq
      receivers.each do |receiver|
        UserNotifierMailer.second_debate_scheduled(@poll, receiver, @random_polls).deliver_now
      end
    end

    def notify_motion_of_censure
      return if @poll.specs['motion_of_censure_notification_sent'] == true
      set_random_polls
      receivers = @poll.votes.map(&:user).uniq
      receivers.each do |receiver|
        UserNotifierMailer.motion_of_censure(@poll, receiver, @random_polls).deliver_now
      end
    end

    def notify_agreemen_sanction
      return if @poll.specs['agreement_sanction_notification_sent'] == true
      set_random_polls
      receivers = @poll.votes.map(&:user).uniq
      receivers.each do |receiver|
        UserNotifierMailer.agreement_sanction(@poll, receiver, @random_polls).deliver_now
      end
    end

    def related_users
      # only notify users that already voted for polls that have the same author or any tag in common
      @related_by_author = Poll.includes(:tags, votes: [:user]).related_by_author(@poll.user)
      @related_by_theme = Poll.includes(:tags, votes: [:user]).related_by_theme(@poll.tag_ids)
      related_polls = [*@related_by_theme, *@related_by_author].uniq
      related_users = related_polls.each_with_object([]) do |poll, receivers|
        receivers << poll.votes.map(&:user)
      end
      related_users.to_a.flatten.uniq
    end

    def bind_links
      @poll = Poll.new(poll_params) unless @poll
      set_project_link
      @poll.related_links.destroy_all if @poll.external_links.present? && links_param != ""
      links_param.split(',').map(&:strip).uniq.each do |url|
        if url.length > 4
          ExternalLink.create!(url: url, poll: @poll)
        end
      end
    end

    def set_project_link
      unless project_link_param[:project_link].blank?
        @poll.project_link.destroy if @poll.project_link
        ExternalLink.create!(url: project_link_param[:project_link], poll: @poll, is_project_link: true)
      end
    end

    def set_poll
      @poll = Poll.includes(:tags, votes: [:user]).find_by(id: params[:id] || params[:poll_id])
    end

    def set_tags
      @poll.set_tags(tags_param)
    end

    def tags_param
      params[:poll][:tags]
    end

    def links_param
      params[:poll][:links]
    end

    def project_link_param
      params[:poll].permit(:project_link)
    end

    def poll_params
      params.require(:poll).permit(
        :closing_date,
        :closing_hour,
        :description,
        :poll_image,
        :poll_image_cache,
        :title,
        :objective,
        :status,
        :state,
        :poll_type,
        :summary,
        :question,
        :user_id,
        vote_types_attributes: [:name]
      )
    end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  include PollsHelper
  before_action :check_if_is_publish_link, only: :show
  before_action :set_poll, only: :show
  before_action :set_random_polls, only: :show
  before_action :set_metas, only: :show
  before_action :set_status_image, only: :show

  def index
    @polls_by_year = Poll.active.includes(:votes, :tags).group_by { |m| m.created_at.year}.sort.reverse.to_h
  end

  def show
    @tag = @poll.default_tag
    @author = @poll.user
  end

  private

  def set_status_image
    @status_image = if @poll.read_attribute_before_type_cast(:poll_type) == 0
      Rails.application.config.cp_base_image_url
    else
      Rails.application.config.pa_base_image_url
    end

    if  @poll.read_attribute_before_type_cast(:state).present?
      @status_image += @poll.read_attribute_before_type_cast(:state).to_s + ".png"
    else
      @status_image += "0.png"
    end
  end

  def set_poll
    @poll = Poll.includes(:tags, :user).find_by(id: params[:id])
    unless @poll
      flash[:error] = "la propuesta no existe"
      redirect_to root_path
    end
    if !@poll.active? && !current_user.try(:administrador?)
      flash[:error] = "la propuesta no está abierta a votación"
      redirect_to root_path
    end
  end

  def check_if_is_publish_link
    if params[:publish_link] && !current_user.try(:administrador?)
      flash[:error] = "Debes iniciar sesión como administrador para aprobar la propuesta para su publicación"
      redirect_to root_path
    end
  end
end

app/helpers/polls_helper.rb
module PollsHelper
  def set_metas
    set_meta_tags og: {
      title: @poll.title,
      url: request.url,
      image: {
        _: @poll.poll_image,
        width: 600,
        height: 600
      },
      description: @poll.summary,
      type: "article",
      site_name: "seamOS Bueanaventura"
    }

    set_meta_tags article: {
      published_time:    @poll.created_at,
      section:           @poll.tags.first.name,
      tag:               @poll.tags.first.name,
    }

    set_meta_tags twitter: {
      card:  "summary_large_image",
      site:  "@seamos",
      title:  @poll.title,
      description: @poll.summary ? @poll.summary.first(199) : nil,
      creator: "@seamos",
      image: {
        _:      @poll.poll_image,
        width:  100,
        height: 100,
      }
    }
  end
end

app/views/admin/polls/_form.html.erb
<%= tinymce_assets %>
<%= form_for([:admin, poll], html: { multipart: true } ) do |f| %>
<%= render 'shared/mensajes_de_error',  object: f.object %>

<div class="radio_button_field">
    <%= f.label "Tipo de propuesta" %><br/>
  <div class="radio-buttons">
    <%= f.radio_button :poll_type, "Voto o proyecto de acuerdo" %>
    <%= f.label :poll_type, "Voto o proyecto de acuerdo"%><br/>
    <%= f.radio_button :poll_type, "Control político", checked: "#{poll && poll.poll_type == 'Control político' ? 'checked' : false}" %>
    <%= f.label :role_type, "Control político",class: "radio_button_lbl"  %>
  </div>
</div>

<br />
<% unless current_user.politico? %>
  <% if f.object.poll_type == "Control político" %>
    <div class="field politician-field politic-control">
      <%= f.label "Estado de la Propuesta" %>
      <%= f.select(:state) do %>
        <% [['Votación seamos', "Votación seamos"], ['Radica concejal', "Radica concejal"], ['Primer debate', "Primer debate"], ['Debate de control político', "Segundo debate"], ['Moción de censura', 'Sanción del proyecto de acuerdo']].each do |c| %>
          <%= content_tag(:option, c.first, value: c.last, selected: f.object.state == c.last ? 'selected' : false) %>
        <% end %>
      <% end %>
    </div>
    <div class="field politician-field vote-or-agreement hidden">
      <%= f.label "Estado de la Propuesta" %>
      <%= f.select :state, Poll.states.keys, {}, {class: 'form-control', id: 'vote-agreement-select'} %>
    </div>
  <% else %>
    <div class="field politician-field politic-control hidden">
      <%= f.label "Estado de la Propuesta" %>
      <%= f.select(:state) do %>
        <% [['Votación seamos', "Votación seamos"], ['Radica concejal', "Radica concejal"], ['Primer debate', "Primer debate"], ['Debate de control político', "Segundo debate"], ['Moción de censura', 'Sanción del proyecto de acuerdo']].each do |c| %>
          <%= content_tag(:option, c.first, value: c.last, selected: f.object.state == c.last ? 'selected' : false) %>
        <% end %>
      <% end %>
    </div>
    <div class="field politician-field vote-or-agreement">
      <%= f.label "Estado de la Propuesta" %>
      <%= f.select :state, Poll.states.keys, {}, {class: 'form-control', id: 'vote-agreement-select'} %>
    </div>
  <%end%>
<%end%>

<div class="field">
    <%= f.label "Título (140 caractéres máximo)" %>
    <%= f.text_field :title, class: 'form-control', maxlength: 140 %>
</div>

<div class="field">
  <%= f.label "sumario" %>
  <%= f.text_area :summary, class: 'form-control' %>
</div>


<div class="field description">
  <%= f.label :description %>
  <%= f.text_area :description, id: 'poll-description',class: 'form-control tinymce', maxlength: 3000 %>
</div>

<div class='spacer-mid'></div>

<%= f.label "Enlace Del Proyecto (opcional)" %>

<div>
 <%= f.text_field :project_link, id: 'project_link', class: "form-control",  placeholder: "Enlace del Proyecto", value: poll.project_link ? poll.project_link.url : ''%>
</div>

<%= f.label "Enlaces Externos (opcionales)" %>
<div>
 <input id="link-1" type="text" class="form-control extlink" placeholder="Enlace externo 1" value="<%= (poll.related_links[0].present? ? poll.related_links[0].url : '') %>" >
</div>

<div>
 <input id="link-2" type="text" class="form-control extlink" placeholder="Enlace externo 2" value="<%= (poll.related_links[1].present? ? poll.related_links[1].url : '') %>" >
</div>

<div>
 <input id="link-3" type="text" class="form-control extlink" placeholder="Enlace externo 3" value="<%= (poll.related_links[2].present? ? poll.related_links[2].url : '') %>" >
</div>

<div class="field" style="display: none">
  <% if @used_links %>
    <%= f.text_field :links, id: 'links-field', value: @used_links%>
  <% else %>
    <%= f.text_field :links, id: 'links-field'%>
  <% end %>
</div>

<div class="field" style="display: none">
    <% if @used_tags %>
      <%= f.text_field :tags, id: 'tags-field', value: @used_tags%>
    <% else %>
      <%= f.text_field :tags, id: 'tags-field'%>
    <% end %>
</div>

<div class="field">
  <%= f.label :objective %>
  <%= f.text_field :objective, class: 'form-control' %>
</div>

<div class="field">
    <%= f.label :closing_date %>
    <input type="text" value="<%= poll.closing_date %>" data-provide='datepicker' data-date-language="es" data-date-autoclose="true" data-date-format="yyyy/mm/dd" class="input-sm form-control" name="poll[closing_date]"/>
</div>

<div class="field">
    <%= f.label "Hora de cierre" %>
    <%= f.time_field :closing_hour, class: 'form-control', value: poll.closing_hour %>
</div>

<div class="field">
    <%= f.label "Imagen principal" %>
    <% if poll.poll_image.file %>
    <p class="has_media">
        <%= t('.has_image', filename: poll.poll_image.file.filename) %>
    </p>
    <% end %>
    <%= f.file_field :poll_image %>
    <%= f.hidden_field :poll_image_cache %>
</div>

<div class="tags-picker">
    <%= f.label "seleccion de temas" %><br>
    <div class="alert alert-info alert-dismissable">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        Selecciona los temas que mejor se adecúen a tu propuesta
    </div>
    <% @location_from = 'new_poll' %>
    <%= render 'admin/tags/tag_list', tags: Tag.all%>
</div>
<div>
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="actions">
    <%= f.submit(data: {disable_with: I18n.t(:processing)}, class: "btn btn-primary", id: "submit-poll", style: "margin-bottom: 150px;") %>
</div>

<% end %>
<script type="text/javascript">
    function addOption() {
        var optionsContainer = $("#vote_types_attributes");
        var childrenCount = optionsContainer.children().length;
        // #ToDo add DELETE option && error takes previous values
        var myHTML = `<input type='text' placeholder='<%= t('.new_option')%>' name='poll[vote_types_attributes][${childrenCount}][name]' id='poll_vote_types_attributes_${childrenCount}_name'>`;

        optionsContainer.append(myHTML);
    }
</script>
<%= tinymce %>

app/views/admin/polls/_poll.html.erb
<div class="row">
  <div class="col-md-12 admin-poll">
    <div class='spacer-small'></div>
    <div class="row">
      <div class="col-md-12 center">
        <h4>
          <strong>
            <%= link_to poll_path(poll) do %>
              <%= poll.title%>
            <% end %>
          </strong>
        </h4>
      </div>
      <div id="poll-status" class="col-md-12">
        <% if !poll.closed?%>
          <i class="material-icons mdl-list__item-avatar active">done</i>
          <span>
            <%= "Propuesta abierta" %>
          </span>
        <% else %>
          <i class="material-icons mdl-list__item-avatar inactive">clear</i>
          <span>
            <%= "Propuesta cerrada" %>
          </span>
        <% end %>
        <span>
          <%= "| #{poll.active? ? 'Aprobada (publicada)' : 'Sin Aprobar (no publicada)'}" %>
        </span>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-3">
        <%= link_to poll_path(poll) do %>
          <img src="<%= poll.poll_image %>" style='width: 100%; ' alt="">
        <% end %>
      </div>
      <div class="col-md-9">
        <p style="max-height: 75px; overflow: hidden">
          <%= poll.description.first(500).html_safe %>
        </p>
        <ul class="list-inline list-unstyled">
          <%poll.tags.each do |tag| %>
            <li class="badge badge-secondary">
              <%=tag.name%>
            </li>
          <%end%>
        </ul>
        <ul class="list-inline list-unstyled">
          <% if current_user.administrador? || current_user.politico?%>
            <span>
              <%= link_to "Editar propuesta" , edit_admin_poll_path(poll.id), class: "btn btn-info" %>
            </span>
            <span>
              <%= link_to "Eliminar propuesta", admin_poll_path(poll.id), class: "btn btn-danger", method: :delete, data: {confirm: t(".confirmation")}  %>
            </span>
            <% if current_user && current_user.administrador? %>
              <span>
                <%= link_to  (poll.active? ? "Ocultar propuesta" : "Publicar propuesta") , admin_poll_toggle_active_flag_path(poll), method: :patch, data: {confirm: poll.active? ? t(".hide_poll?") : t(".publish_poll?")}, class: 'btn btn-info' %>
              </span>
            <% end %>
          <% end %>
          <br>
          <span>
            cierre:
            <%= poll.closing_date %>
          </span>
          <span>
            | creación:
            <%= poll.created_at.to_date %>
          </span>
          <span>
            | última actualización:
            <%= poll.updated_at.to_date %>
          </span>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class='spacer-small'></div>

app/views/admin/polls/edit.html.erb
<div class='spacer-big'></div>
<h1> Editar propuesta </h1>

<div class="col-md-6 margin-auto">
  <%= render 'form', poll: @poll %>
</div>

app/views/admin/polls/index.html.erb
<div id="polls-index" class='container'>
  <br><br>
  <div class="row">
    <div class="col-md-3 admin-search-form">
      <%= label_tag "Filtros" %>
      <%= form_tag({controller: "admin/polls", action: "index"}, method: "get") do %>
      <%= select_tag(:status, options_for_select({'Todas': "all", 'En votación': "open", 'Cerradas': "closed", 'Sin publicar': "inactive"}, params[:status] ), {class: "form-control"}) %>
      <%= text_field_tag :search_term, params[:search_term], class: 'form-control', placeholder: 'Búsqueda por Título' %>
      <%= submit_tag 'Filtrar', class: 'form-control btn-info' %>
      <% end %>
    </div>
    <div class="col-md-9">
      <% if @polls.length > 0 %>
        <%= render partial: "poll", collection: @polls %>
      <% else %>
      <div>
        <h2> No hay resultados </h2>
      </div>
      <% end %>
    </div>
    <div class="col-md-12">
      <h2>
        <%= paginate @polls %>
      </h2>
    </div>
  </div>
</div>

app/views/admin/polls/new.html.erb
<div class='spacer-big'></div>
<h1> Crear propuesta </h1>

<div class="col-md-6 margin-auto">
  <%= render 'form', poll: @poll %>
</div>