config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  constraints subdomain: 'www' do
    get ':any', to: redirect(subdomain: nil, path: '/%{any}'), any: /.*/
  end

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: "prehome#index"
  get 'settings/unsubscribe'
  get '/home', to: 'home#index'
  get '/politicians', to: 'pages#politicians'
  get '/terms', to: 'pages#terms'
  get '/diplomado-innovacion-politica', to: 'pages#diplomat'
  get '/partidos-politicos-en-la-era-digital', to: 'pages#digital_era', as: 'digital_era'
  get '/mapeo-de-infraestructuras-civicas', to: 'pages#maping', as: 'maping'

  namespace :admin do
    resources :tags
    resources :polls, except: [:show] do
      patch 'toggle_active_flag'
    end
    resources :users, only: [:index, :edit, :update, :destroy] do
      collection do
        get 'permits'
      end
    end
    resources :dashboard, only: [:index]
    get '/dashboard/stats', to: 'dashboard#stats'
  end

  resources :subscriptions, only: [:create, :destroy]
  resources :users , except: [:show] do
    get 'already_voted', on: :member
    get 'validate', on: :member
    patch 'update_valid_user', on: :member
    post 'interests', to: 'interests#association', format: 'json'
  end

  get '/check_session', to: 'sessions#show', format: 'json'
  delete '/sessions', to: 'sessions#destroy', as: 'session'
  delete '/destroy_facebook_session', to: 'sessions#destroy_facebook_session'
  post '/sessions', to: 'sessions#create', format: 'json'
  get '/mail_preview', to: 'messages#preview'

  get '/auth/sessions', to: 'sessions#error'
  resources :users, only: [:show]
  get '/proponents/:id', to: 'users#politician_profile', as: :politician_profile
  get 'polls/closed', to: 'polls#index_closed', format: 'json'
  get 'check_vote', to: 'votes#check_vote', format: 'json'
  get 'random_polls', to: 'polls#random_non_voted_polls', format: 'json'
  get 'summary_polls', to: 'polls#summary_polls', format: 'json'

  resources :polls do
    get 'last', on: :collection
    get 'voted', on: :collection
    get 'search', on: :collection, to: 'polls#search'
  end

  resources :votes, only: :create
  resources :tags, only: [:show, :index]
  resources :admin, only: [:create, :new, :edit]
  scope '/admin', as: :admin do
    resources :email_lists
    get '/mail', to: 'messages#new'
    post '/mail', to: 'messages#create'
    get '/mail_preview', to: 'messages#preview'
    # get '/', to: 'sessions#new'
    get '/', to: 'sessions#new', as: :login
    post '/sessions', to: 'sessions#admin_create'
    get 'validate-users', to: 'admin/users#index'
  end

  get 'settings/unsubscribe'
  get 'settings/successfully_unsubscribed'
  patch 'settings/update'

  mount SimpleDiscussion::Engine => "/foro"
end

app/models/email_list.rb
# == Schema Information
#
# Table name: email_lists
#
#  id         :integer          not null, primary key
#  name       :string
#  identifier :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class EmailList < ApplicationRecord
  attr_accessor :raw_mail_list
  has_many :subscriptions, dependent: :destroy

  def create_subscriptions(mail_list)
    mail_list.split(',').each do |mail|
      Subscription.create(email: mail.strip, email_list_id: id)
    end
  end
end

app/controllers/email_lists_controller.rb
class EmailListsController < ApplicationController
  before_action :email_list_params, only: :set_email_lists
  before_action :validate_superadmin

  def new
    @email_list = EmailList.new
  end

  def index
    @email_lists = EmailList.all
  end

  def create
    @email_list = EmailList.new(email_list_params)
    if @email_list.save
      begin
        @email_list.create_subscriptions(email_list_params[:raw_mail_list])
      rescue
        flash[:error] = "La lista no pudo ser creada"
      end
      flash[:success] = "lista creada con éxito"
      redirect_to admin_email_lists_path and return
    else
      flash[:error] = "La lista no pudo ser creada"
      render :new and return
    end
  end

  def destroy
    @email_list = EmailList.find_by(id: params[:id])
    @email_list.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def email_list_params
    params.require(:email_list).permit(:name, :raw_mail_list)
  end
end

app/views/email_lists/edit.html.erb
<h1> <%= t ('.')%> <%= t ('.email_list') %></h1>
<div class="col-md-6 col-md-offset-3">
  <%= render 'form', email_list: @email_list %>
</div>

app/views/email_lists/index.html.erb
<div id='email_list_index' class="col-md-8 margin-auto">
  <br>
  <div id='new-list-button-container'>
    <%= link_to "crear nueva lista", new_admin_email_list_path, class: 'btn btn-info' %>
  </div>
  <br><hr><br>
  <div class="email-list">
    <div class="email-lists-container">
      <% @email_lists.reverse_each do |email_list|%>
        <h1>
          <%= email_list.name %>
          <span class="delete">
            <%= link_to admin_email_list_path(email_list.id), title: "Eliminar Lista", method: :delete, data: {confirm: "está seguro de que desea eliminar la lista #{email_list.name}?"} do %>
            <i class="fa fa-user-times"></i>
            <% end %>
          </span>
        </h1>
        <div class="subscribers-container">
          <% email_list.subscriptions.reverse_each do |subscription|%>
            <span class="content" style="border-right: 1px solid black; padding: 0 10px">
              <span style='white-space: nowrap'>
                <span class="name">
                  <%= subscription.email %>
                </span>
                <span class="options">
                  <span class="delete">
                    <%= link_to subscription_path(subscription.id), title: "Eliminar Usuario de la lista", method: :delete, data: {confirm: "está seguro de que desea eliminar el correo #{subscription.email}?"} do %>
                    <i class="fa fa-minus-square"></i>
                    <% end %>
                  </span>
                </span>
              </span>
            </span>
          <%end%>
        </div>
        <br><hr><br>
      <%end%>
    </div>
  </div>
</div>

app/views/email_lists/new.html.erb
<h1> Crear nueva lista de correos </h1>

<div class="col-md-6 margin-auto">
  <%= form_for [:admin, @email_list] do |f| %>
    <%= render 'shared/mensajes_de_error',  object: f.object %>
    <div class="field">
      <%= f.label "Nombre de la lista" %>
      <%= f.text_field :name, class: 'form-control',  autofocus: true %>
    </div>
    <div class="field">
      <%= f.label "Lista de correos" %>
      <%= f.text_area :raw_mail_list, class: 'form-control',  autofocus: true %>
    </div>
    <div class="field">
      <%= f.submit "Guardar lista" %>
    </div>
  <% end %>
</div>