config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  constraints subdomain: 'www' do
    get ':any', to: redirect(subdomain: nil, path: '/%{any}'), any: /.*/
  end

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: "prehome#index"
  get 'settings/unsubscribe'
  get '/home', to: 'home#index'
  get '/politicians', to: 'pages#politicians'
  get '/terms', to: 'pages#terms'
  get '/diplomado-innovacion-politica', to: 'pages#diplomat'
  get '/partidos-politicos-en-la-era-digital', to: 'pages#digital_era', as: 'digital_era'
  get '/mapeo-de-infraestructuras-civicas', to: 'pages#maping', as: 'maping'

  namespace :admin do
    resources :tags
    resources :polls, except: [:show] do
      patch 'toggle_active_flag'
    end
    resources :users, only: [:index, :edit, :update, :destroy] do
      collection do
        get 'permits'
      end
    end
    resources :dashboard, only: [:index]
    get '/dashboard/stats', to: 'dashboard#stats'
  end

  resources :subscriptions, only: [:create, :destroy]
  resources :users , except: [:show] do
    get 'already_voted', on: :member
    get 'validate', on: :member
    patch 'update_valid_user', on: :member
    post 'interests', to: 'interests#association', format: 'json'
  end

  get '/check_session', to: 'sessions#show', format: 'json'
  delete '/sessions', to: 'sessions#destroy', as: 'session'
  delete '/destroy_facebook_session', to: 'sessions#destroy_facebook_session'
  post '/sessions', to: 'sessions#create', format: 'json'
  get '/mail_preview', to: 'messages#preview'

  get '/auth/sessions', to: 'sessions#error'
  resources :users, only: [:show]
  get '/proponents/:id', to: 'users#politician_profile', as: :politician_profile
  get 'polls/closed', to: 'polls#index_closed', format: 'json'
  get 'check_vote', to: 'votes#check_vote', format: 'json'
  get 'random_polls', to: 'polls#random_non_voted_polls', format: 'json'
  get 'summary_polls', to: 'polls#summary_polls', format: 'json'

  resources :polls do
    get 'last', on: :collection
    get 'voted', on: :collection
    get 'search', on: :collection, to: 'polls#search'
  end

  resources :votes, only: :create
  resources :tags, only: [:show, :index]
  resources :admin, only: [:create, :new, :edit]
  scope '/admin', as: :admin do
    resources :email_lists
    get '/mail', to: 'messages#new'
    post '/mail', to: 'messages#create'
    get '/mail_preview', to: 'messages#preview'
    # get '/', to: 'sessions#new'
    get '/', to: 'sessions#new', as: :login
    post '/sessions', to: 'sessions#admin_create'
    get 'validate-users', to: 'admin/users#index'
  end

  get 'settings/unsubscribe'
  get 'settings/successfully_unsubscribed'
  patch 'settings/update'

  mount SimpleDiscussion::Engine => "/foro"
end

app/views/layouts/partials/_admin_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between" id="admin-navbar">
  <%= link_to root_path, id: 'logo', class: 'navbar-brand' do %>
    <%= image_tag "LogoSeamos.png" %>
  <% end %>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto" id='options'>
      <li class="nav-item"><%= link_to 'Propuestas', admin_polls_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Foro', simple_discussion_path, class: 'nav-link' %></li>
      <% if current_user.politico? %>
        <li class='nav-item'><%= link_to 'Crear Propuesta', new_admin_poll_path, class: 'nav-link' %></li>
        <li class='nav-item'><%= link_to 'Editar información de perfil', edit_admin_user_path(current_user), class: 'nav-link' %></li>
      <% end %>
      <% if current_user.administrador? %>
        <li class="nav-item"><%= link_to 'Usuarios', admin_validate_users_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Temas', new_admin_tag_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to "Datos", admin_dashboard_stats_path, class: 'nav-link' %> </li>
        <li class="nav-item"><%= link_to "Permisos", permits_admin_users_path, class: 'nav-link' %> </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Emails
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Listas de Emails", admin_email_lists_path, class: 'dropdown-item'%>
            <%= link_to "Nuevo Email", admin_mail_path, class: 'dropdown-item'%>
          </div>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
          cerrar sessión
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/partials/_blog_widget.html.erb
<div id="blog-info">
  <div id="bi-title">
    BLOG
  </div>
  <div class='subtitle'>
    ÚLTIMAS PUBLICACIÓNES
  </div>
  <div id=posts-container-wrapper>
    <div id='posts-container'>
      <% blog_posts.each do |bp| %>
      <div class='blog-post'>
        <div class='bp-date'>
          <div class='bp-date-day'>
            <%= l(bp["date"].to_date, format: '%d') %>
          </div>
          <div class='bp-date-month'>
            <%= l(bp["date"].to_date, format: '%B').first(3) %>
          </div>
        </div>
        <div class="date-edge"></div>
        <div class='bp-title'>
          <%= bp["title"] %>
        </div>
        <br>
        <div class="link-wrapper">
          <%= link_to bp["url"], target: '_blank' do %>
          LEER
          <i class="fa fa-eye"></i>
          <% end %>
        </div>
      </div>
      <hr>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/partials/_candidate_options.html.erb
<nav>
  <li>  
    <%= link_to 'Modificar información de perfil', edit_admin_user_path(current_user) %> 
  </li>
  <li>  
    <%= link_to 'Crear Propuesta', new_admin_poll_path %> 
  </li>
  <li>
    <%= link_to destroy_user_session_path, method: :delete do %>
      SALIR
    <% end %>
  </li>
</nav>

app/views/layouts/partials/_client_navbar.html.erb
<div id="client-navbar">
  <header>
    <%= link_to  image_tag('LogoSeamos_blanco.png', class: 'campaign-logo'), root_path %>
    <% if current_user.present? %>
      <div class="hide-on-desktop only-photo">
        <%= image_tag current_user.resolve_photo, class: 'navbar-photo' %>
      </div>
    <% end %>
    <a id='hamburger'>
      <i class="fa fa-bars"></i>
    </a>
    <span id='top-nav' class="hide-on-mobile">
      <%= render 'layouts/partials/normal_user_options' %>
    </span>
    <span id='hide-side-nav' class="hide-on-desktop"></span>
    <span id='side-nav', class='hide-on-desktop'>
      <%= render 'layouts/partials/normal_user_options' %>
    </span>
  </header>
</div>

app/views/layouts/partials/_footer.html.erb
<% if session[:session_type] == nil %>
  <div id="client-footer">
    <div class="hide-on-desktop-terms">
      <%= link_to terms_path do %>
        <span id="who-text-mobile"> TÉRMINOS Y CONDICIONES </span>
      <% end %>
      <br>
      <br>
      <br>
    </div>
    <div class="logo-container">
      <div class="logo-background">
        <div class="logo">
          <br>
          <br>
        </div>
        <%= link_to terms_path do %>
          <span class="who-text"> TÉRMINOS Y CONDICIONES </span>
        <% end %>
        <br>
        <div id="who-are-we">
          <span id="footer-social-icons-container">
            <a class="footer-social-icon" href="https://www.facebook.com/seamoscolombia/" target="_blank" rel="noopener noreferrer">
              <i class="fa fa-facebook" aria-hidden="true"></i>
            </a>
            <a class="footer-social-icon" href="https://twitter.com/seamos" target="_blank" rel="noopener noreferrer">
              <i class="fa fa-twitter" aria-hidden="true"></i>
            </a>
            <a class="footer-social-icon" href="https://www.instagram.com/seamoscolombia/" target="_blank" rel="noopener noreferrer">
              <i class="fa fa-instagram" aria-hidden="true"></i>
            </a>
            <a class="footer-social-icon" href="https://www.youtube.com/channel/UCC8EUjRTWhzELH3_iypQQ8w" target="_blank" rel="noopener noreferrer">
              <i class="fa fa-youtube" aria-hidden="true"></i>
            </a>
          </span>
        </div>
      </div>
    </div>
    <div class="disclaimer-container">
      <br>
      <span class="disclaimer">Copyright 2017 SeamOS Democracia Digital</span>
    </div>
  </div>
<% end %>

app/views/layouts/partials/_forum_widget.html.erb
<div class="MultiCarousel hh" data-items="1,3,4,4" data-slide="1" id="MultiCarousel" data-interval="1000">
  <div class="MultiCarousel-inner">
    <% discussions.each do |discussion| %>
    <div class="item">
      <div class="pad15 single-on-mobile">
        <p class="lead"><%= discussion.title %></p>
        <%= link_to simple_discussion.forum_thread_path(discussion), class: 'discussion-link' do %>
          Leer
          <i class="fa fa-eye"></i>
        <% end %>
      </div>
    </div>
    <% end %>
    <% 4.times do %>
      <div class="item">
        <div class="pad15 disabled">
        </div>
      </div>
    <% end %>
  </div>
  <button class="leftLst hh">
<<<<<<< HEAD
    <%= image_tag  "b-card-carousel-handlers-l", class: 'rightLST' %>
  </button>
  <button class="rightLst hh">
    <%= image_tag  "b-card-carousel-handlers-r", class: 'rightLST' %>
=======
    <%= image_tag  "b-card-carousel-handlers-l.png", class: 'rightLST' %>
  </button>
  <button class="rightLst hh">
    <%= image_tag  "b-card-carousel-handlers-r.png", class: 'rightLST' %>
>>>>>>> 1ba56361c5dfee263c147d37a1a8ccfd3a0a4242
  <button>
</div>

app/views/layouts/partials/_newsletter.html.erb
<div id="homepage" class="flex-container">
  <div class="newsletter-container">
    <div class="title">Suscríbete a nuestro Boletín informativo</div>
    <div class="newsletter">
      <%= form_for(Subscription.new) do |form| %>
      <div class="input-group">
        <%= form.text_field :email, class: "form-control", placeholder: "correo" %>
        <span class="input-group-btn">
          <%= form.button "ENVIAR", class: "btn btn-secondary", type: 'submit'%>
        </span>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/partials/_normal_user_options.html.erb
<nav>
  <li>
    <%= link_to  "TEMAS", root_path(anchor: 'tvtd') %>
  </li>
  <li>
    <a href="http://sifuerapresidente.co" target="_blank" rel="noopener noreferrer"> SIFUERAPRESIDENTE </a>
  </li>
  <li id="this" class="hide-on-mobile">
    <%= link_to 'QUIENES SOMOS', root_path(anchor: 'who-are-we') %>
  </li>
  <li>
    <a href="https://seamosit.github.io" rel="noopener noreferrer"> BLOG</a>
  </li>
  <li>
    <%= link_to  "FORO", simple_discussion_path %>
  </li>
  <li id="politicians-link">
    <%= link_to  "CONCEJALES", root_path(anchor: 'councilors') %>
  </li>
  <% if user_signed_in? %>
    <div>
      <%= link_to user_path(current_user), class: 'profile-button' do %>
        <%= image_tag  current_user.resolve_photo, class: 'navbar-photo' %>
          TU PERFIL
        <% end %>
    </div>
    <li>
      <%= link_to destroy_user_session_path, method: :delete do %>
        SALIR
        <% end %>
    </li>
    <% else %>
      <div class="hide-on-mobile">
        <li class="dropdown">
          <button class="nav-with-background" type="button" data-toggle="dropdown" aria-expanded="false">
            REGÍSTRATE
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu custom-dropdown">
            <li>
              <span style="transition: opacity 0.5s;">
                <form class="button_to" method="post" action="/users/auth/facebook">
                  <button class="loginBtn loginBtn--facebook metro" type="submit">
                    Continuar con facebook
                  </button>
                  <input type="hidden" name="authenticity_token" value="8cov2NI86UF1R1uIPk+PNyXX0Yo0CNj3d8a5qJuVo06Tu9FlfPS778wO2XDf+gxAjvgwsv7B+gisLoy5p5vQZA==">
                </form>
              </span>
            </li>
            <li role="presentation" class="divider"></li>
            <li>
              <div>
                <form class="button_to" method="post" action="/users/auth/google_oauth2">
                  <button class="loginBtn loginBtn--google" type="submit">
                    Continuar con google
                  </button>
                  <input type="hidden" name="authenticity_token" value="8cov2NI86UF1R1uIPk+PNyXX0Yo0CNj3d8a5qJuVo06Tu9FlfPS778wO2XDf+gxAjvgwsv7B+gisLoy5p5vQZA==">
                </form>
              </div>
            </li>
            <li>
              <div>
                <%= button_to new_user_session_path, class: "loginBtn loginBtn--email" do %>
                  Continuar con email
                <% end %>
              </div>
            </li>
          </ul>
        </li>
      </div>
        <li class='hide-on-desktop'>
          <%= button_to user_facebook_omniauth_authorize_path, class: "loginBtn loginBtn--facebook metro" do %>
            Continuar con facebook
          <% end %>
        </li>
        <li class='hide-on-desktop'>
          <%= button_to user_google_oauth2_omniauth_authorize_path, class: "loginBtn loginBtn--google" do %>
            Continuar con google
          <% end %>
        </li>
        <li class='hide-on-desktop'>
          <%= button_to new_user_session_path, class: "loginBtn loginBtn--email" do %>
            Continuar con email
          <% end %>
        </li>

      <% end %>
</nav>

app/views/layouts/partials/_politician_options.html.erb
<nav>
  <li>  
    <%= link_to 'Modificar información de perfil', edit_admin_user_path(current_user) %> 
  </li>
  <li>  
    <%= link_to 'Crear Propuesta', new_admin_poll_path %> 
  </li>
  <li>
    <%= link_to destroy_user_session_path, method: :delete do %>
      SALIR
    <% end %>
  </li>
</nav>

app/views/layouts/partials/_politicians.html.erb
<div class="politicians col-12">
  <% politicians.each do |politician| %>
    <%= link_to politician_profile_path(politician["production_id"]), class: 'politician-link' do %>
      <div class="politician <%= politician["background_class"] %>">
        <div class="photo"></div>
        <div class="name"><%= politician["name"] %></div>
        <div class="organization"><%= politician["party"] %></div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/partials/_tags_widget.html.erb
<div class="row">
  <div class="MultiCarousel hh" data-items="2,4,6,7" data-slide="1" id="MultiCarousel" data-interval="1000">
    <div class="MultiCarousel-inner">
      <%if tags.present? %>
        <% tags.each do |tag| %>
        <div class="item">
          <div class="pad15">
            <%= link_to tag_path(tag) do %>
              <%= image_tag tag.thumbnail.url %>
              <p class="lead"><%= tag.name %></p>
            <% end %>
          </div>
        </div>
        <% end %>
        <% 7.times do %>
          <div class="item">
            <div class="pad15 disabled">
              <%= image_tag tags.first.thumbnail.url, style: "visibility: hidden" %>
            </div>
          </div>
        <% end %>
      <% else %>
        <% 10.times do %>
          <div class="item">
            <div class="pad15 disabled">

            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <button class="leftLst hh">
<<<<<<< HEAD
      <%= image_tag  "b-card-carousel-handlers-l", class: 'rightLST' %>
    </button>
    <button class="rightLst hh">
      <%= image_tag  "b-card-carousel-handlers-r", class: 'rightLST' %>
=======
      <%= image_tag  "b-card-carousel-handlers-l.png", class: 'rightLST' %>
    </button>
    <button class="rightLst hh">
      <%= image_tag  "b-card-carousel-handlers-r.png", class: 'rightLST' %>
>>>>>>> 1ba56361c5dfee263c147d37a1a8ccfd3a0a4242
    <button>
  </div>
</div>

app/views/layouts/partials/_you_may_also_like.html.erb
<% if @random_polls.present?  %>
  <div>
    <div class="row interest-banner one-mod">
      También te puede interesar
    </div>
    <div id="may-interest-container">
      <div id="may-interest">
        <% @random_polls.each do |poll| %>
          <%= render partial: 'polls/partials/poll_small_preview', locals: {poll: poll, from_ymal: true} %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>